In [12]:
import pandas as pd
import yfinance as yf
import matplotlib as mp
import numpy as np

In [19]:
Close = yf.download("AAPL")
AAPL_Close = Close["Close"]
print(AAPL_Close.iloc[13])
AAPL_Close

[*********************100%***********************]  1 of 1 completed

Ticker
AAPL    315.320007
Name: 2026-07-10 00:00:00, dtype: float64

Ticker            AAPL
Date
2026-06-22  297.010010
2026-06-23  294.299988
2026-06-24  293.079987
2026-06-25  275.149994
2026-06-26  283.779999
2026-06-29  281.739990
2026-06-30  289.359985
2026-07-01  294.380005
2026-07-02  308.630005
2026-07-06  312.660004
2026-07-07  310.660004
2026-07-08  313.390015
2026-07-09  316.220001
2026-07-10  315.320007
2026-07-13  317.309998
2026-07-14  314.859985
2026-07-15  327.500000
2026-07-16  333.260010
2026-07-17  333.739990
2026-07-20  326.589996
2026-07-21  327.739990
2026-07-22  324.450012

In [8]:
#Calculate single day simple moving average (For EMA, MACD, etc.) 14 day period
Period = AAPL_Close.tail(14)
print(Period)

SMA = Period.sum() / 14
SMA

Ticker            AAPL
Date
2026-07-02  308.630005
2026-07-06  312.660004
2026-07-07  310.660004
2026-07-08  313.390015
2026-07-09  316.220001
2026-07-10  315.320007
2026-07-13  317.309998
2026-07-14  314.859985
2026-07-15  327.500000
2026-07-16  333.260010
2026-07-17  333.739990
2026-07-20  326.589996
2026-07-21  327.739990
2026-07-22  324.739105

Ticker
AAPL    320.187079
dtype: float64

In [39]:
#good for graphing, create simple moving average, potentially save into an index and then graph
Moving_Average = AAPL_Close.rolling(window=14).mean()
Moving_Average

Ticker            AAPL
Date
2026-06-22         NaN
2026-06-23         NaN
2026-06-24         NaN
2026-06-25         NaN
2026-06-26         NaN
2026-06-29         NaN
2026-06-30         NaN
2026-07-01         NaN
2026-07-02         NaN
2026-07-06         NaN
2026-07-07         NaN
2026-07-08         NaN
2026-07-09         NaN
2026-07-10  298.977142
2026-07-13  300.427141
2026-07-14  301.895713
2026-07-15  304.354285
2026-07-16  308.505001
2026-07-17  312.073571
2026-07-20  315.277143
2026-07-21  318.018572
2026-07-22  320.190715

In [ ]:
#Working with EMA
k = 2
n = 14
alpha = k / (n + 1)

SMA = Period.sum() / 14

period = AAPL_Close.head(n)
SMA_init = period.sum() / 14

EMA_Rolling = AAPL_Close.tail((len(AAPL_Close) - (n - 1)))
print(EMA_Rolling)


for i in range(0, (len(AAPL_Close) - (n - 1))):
    if i == 0:
        EMA_Previous = SMA_init

    else:
        EMA_Previous = EMA_Current
        
    EMA_Current = ((AAPL_Close.iloc[i + 13]) * alpha) + (EMA_Previous * (1 - alpha))
    EMA_Rolling.iloc[0, 0] = EMA_Current
    
print(EMA_Rolling)

Ticker            AAPL
Date
2026-07-10  315.320007
2026-07-13  317.309998
2026-07-14  314.859985
2026-07-15  327.500000
2026-07-16  333.260010
2026-07-17  333.739990
2026-07-20  326.589996
2026-07-21  327.739990
2026-07-22  324.450012
[315.32000732 317.30999756 314.85998535 327.5        333.26000977
 333.73999023 326.58999634 327.73999023 324.45001221 301.156191
 303.31003187 304.85002567 307.87002225 311.25535392 314.25330543
 315.89819755 317.47710324 318.40682443]

In [18]:
EMA_Rolling.plot()

AttributeError: 'numpy.ndarray' object has no attribute 'plot'